# For PRs.

name: Build and Test

on:
  workflow_call:
  workflow_dispatch:

env:
  # See supported Node.js release schedule at https://nodejs.org/en/about/releases
  NODE_VERSION: 20.x

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
      # While spell check runs in lint, here we run it as a separate step to
      # make it easier to see the results and treat violations as errors
      # instead of warnings.
      - name: Spell Check
        run: npx cspell "**" --no-progress --show-suggestions --show-context

  unitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - run: npm ci
      - run: npm run test:unit

  vsCodeTests:
    name: VS Code Integration Tests
    strategy:
      matrix:
        # macos-latest and windows-latest can be added as we work towards a release.
        # For now, there's no sense acruing the cost of the runners.
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - run: npm ci
      - name: npm run test:integration:headless (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run test:integration:headless
      - name: npm run test:integration
        if: matrix.os != 'ubuntu-latest'
        run: npm run test:integration
